### ISSUE TITLE
Information about CRM application

### ISSUE THREAD

**Issue by dxmano1985** [Balakrishnan-M/crm-app#2]
Dear @Balakrishnan-M, I want to use experiment this code base Can you please update the readme file with the project information. Thank You.

**Comment by Balakrishnan-M** [comment]
> Dear @Balakrishnan-M, I want to use experiment this code base Can you please update the readme file with the project information. Thank You.

Hello @dxmano1985 ,

Good Day, I had updated the readme file with appropriate project information. You can use that. Thanks for notifying me about this. 

Thank you.
